### ISSUE TITLE
fix: sanitize inputs

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/onroutebc#845]
3x security warnings about adding sanitization.

https://github.com/bcgov/onroutebc/security/code-scanning/129
https://github.com/bcgov/onroutebc/security/code-scanning/130
https://github.com/bcgov/onroutebc/security/code-scanning/131

**Comment by cberg-aot** [comment]
Fixed with CodeQL Scan
https://github.com/bcgov/onroutebc/security/code-scanning/129
